### ISSUE TITLE
zweiter WR

### ISSUE THREAD

**Issue by MorreMor** [z-master42/solarflow#1]
Hi,
ich weiß nicht wie ich dich sonst erreiche, daher hier.
Wenn ich einen zweiten WR habe, funktioniert das Skript dann auch?
Ich nutze 3 Module auf einen String WR und zukünftig 2 Module auf einen Hoymiles mit Zendure.
Zielt: String WR deckt Tagesbedarf ab und Hoymiles soll Batterie nach Bedarf laden bzw. entladen.
Habe auch den Shelly 3em. ich denke mal, dass dieser richtig saldieren muss (was er bereits nach Programmierung über Homeassitant tut) um den tatsächlichen Strombedarf zu ermitteln? Danke dir vorab

**Comment by z-master42** [comment]
Ich wüsste nicht warum nicht. Es muss natürlich entsprechend angepasst werden. Kommt drauf an, wie du dir das vorstellst. 
Soll das Skript dann nur für den Hoymiles sein? Kenne deinen String-WR ja nicht. Lässt sich dieser auch über HA steuern, bzw. ein Limit setzen? Wenn du den SF primär nutzt um tagsüber die Akkus zu laden um dann die Grundlast nachst zu decken, kommen sich die beiden WR ja auch nicht in die Quere.

**Comment by MorreMor** [comment]
Genau Skript soll ausschließlich den HM steuern. Was genau müsste ich wie anpassen? Könntest du mir da gegen eine kleine Spende helfen? Mit freundlichen Grüßen Andreas Morawetz Am 15.08.2023 um 09:45 schrieb z-master42 ***@***.***>:﻿
Ich wüsste nicht warum nicht. Es muss natürlich entsprechend angepasst werden. Kommt drauf an, wie du dir das vorstellst.
Soll das Skript dann nur für den Hoymiles sein? Kenne deinen String-WR ja nicht. Lässt sich dieser auch über HA steuern, bzw. ein Limit setzen? Wenn du den SF primär nutzt um tagsüber die Akkus zu laden um dann die Grundlast nachst zu decken, kommen sich die beiden WR ja auch nicht in die Quere.

**Comment by z-master42** [comment]
Dann kann das Skript in der Form erstmal so bleiben (also die Variante, die nur die Nulleinspeisung realisiert). Dann ist es denke ich mal am einfachsten, wenn du das Skript dann zeitabhängig startest und wenn du dann wieder für tagsüber auf den String-WR wechselt, den Hoymiles abschaltest, oder so.

**Comment by MorreMor** [comment]
Hast du schon eine Lösung oder es mal angeschaut?Mit freundlichen Grüßen Mit freundlichen Grüßen Andreas Morawetz Anfang der weitergeleiteten Nachricht:Von: Andreas Morawetz ***@***.***>Datum: 15. August 2023 um 09:46:52 MESZAn: z-master42/solarflow ***@***.***>Betreff: Aw: [z-master42/solarflow] zweiter WR (Issue #1)﻿Genau Skript soll ausschließlich den HM steuern. Was genau müsste ich wie anpassen? Könntest du mir da gegen eine kleine Spende helfen? Mit freundlichen Grüßen Andreas Morawetz Am 15.08.2023 um 09:45 schrieb z-master42 ***@***.***>:﻿
Ich wüsste nicht warum nicht. Es muss natürlich entsprechend angepasst werden. Kommt drauf an, wie du dir das vorstellst.
Soll das Skript dann nur für den Hoymiles sein? Kenne deinen String-WR ja nicht. Lässt sich dieser auch über HA steuern, bzw. ein Limit setzen? Wenn du den SF primär nutzt um tagsüber die Akkus zu laden um dann die Grundlast nachst zu decken, kommen sich die beiden WR ja auch nicht in die Quere.

**Comment by z-master42** [comment]
Siehe meinen Kommentar vor deinem.
