### ISSUE TITLE
Den Wert OutputLimit setzen

### ISSUE THREAD

**Issue by SpongeBorg** [z-master42/solarflow#10]
Hallo z-master42,

erst mal vielen Dank für die Bereitstellung der Informationen. Ich habe ein Zendure Solarflow mit AB1000 und die Einbindung via MQTT-Bridge im Home Assistant funktioniert so was von super - so würde ich das auch vom Solarflow-Support erwarten. Also dafür schon mal alle Daumen hoch :-).

Ich habe eine Frage zur Idee der Nulleinspeisung, weil ich auch so was implementieren möchte. Ich bin nicht ganz sicher, ob die vorgeschlagene Anpassung der Leistung am Mikrowechselrichter (MWR) "sinnvoll" ist? Ich meine, wenn das Solarflow dem MWR 600W zur Vorfügung stellt und dann der MWR nur 200W durchlässt, dann ist das ja Energieverschwendung, oder?

Besser wäre es doch, wenn man das "OutputLimit" am Solarflow-Gerät dem aktuellen Eigenverbrauch anpassen würde (natürlich mit den entsprechenden Limits). Dieser Modus ist in der Zendure-App auch so vorgesehen, aber ich müsste dafür neue SmartPlugs von Shelly kaufen und die Regelung läuft dann auch nicht über meinen HA, sondern über den Zendure-Server.

Gibt es iwie die Möglichkeit, den Wert "OutputLimit" des SolarFlow-Geräts nicht nur auszulesen, sondern auch zu setzen?

Vielen Dank und Beste Grüße

**Comment by z-master42** [comment]
Moin und erstmal Danke.
Verschwendet wird da nichts, da die Limit-Einstellung in der App erstmal egal ist. Der Wechselrichter bestimmt, wie viel er abnimmt, unabhängig von dem, was im Hub als Limit eingestellt ist (außer natürlich, es ist ein kleinerer Wert eingestellt, als das was der Wechselrichter gerne hätte). Das, was am Hub dann "zuviel" vorhanden ist, geht in den Akku.
Wenn am Wechselrichter also nur der Hub hängt, lässt sich eine Nulleinspeisung über Home Assistant am einfachsten über die Drosselung des Wechselrichters realisieren.
Es ist aber dennoch über "Umwege" möglich, das Limit.von außerhalb der App zu setzen. Eine offiziell von Zendure bereitgestellte Möglichkeit kenne ich allerdings nicht.
Mir bekannt sind da die Projekte solarflow-statuspage und solarflow-control von https://github.com/reinhard-brandstaedter. Ersteres habe ich selber mit in der Nutzung.

**Comment by SpongeBorg** [comment]
Hallo, vielen Dank für die schnelle Antwort. Ich habe mir die vorgeschlagenen Seiten mal angesehen. Da wäre ich nie hingekommen ohne deine Hilfe :-).

Leider hat mein MWR keine WLAN-Schnittstelle. Daher bin ich auf eine (aktive) Kommunikation zum Zendure Solarflow angewiesen. Dort kann ich ja per App den Leistungswert zum Haus ganz bequem eingeben. Da ich mein SolarFlow in den Home Assistant via MQTT Bridge eingebunden habe, muss ich mal schauen, wie ich die Kommunikation zum Zendure hinbekomme. Bei SolarFlow-Control bin ich (oberflächlich) fündig geworden. Die MQTT Brücke für das Auffangen der Nachrichten ist ja dank deiner Anleitung schon aufgebaut ... 

Trotzdem vielen Dank noch mal für deine pro-aktive Antwort. Wenn ich erfolgreich bin, dann gebe ich dir hier Bescheid. Ansonsten kann das Issue gern geschlossen werden. 

Beste Grüße ...
