### ISSUE TITLE
MQTT

### ISSUE THREAD

**Issue by hphde** [z-master42/solarflow#12]
Guten Morgen,

Ich hatte bereits eine MQTT Instanz, daher habe ich die Bridge konfiguriert. Das hat geklappt und kann auch Daten via MQTT-Explorer sehen.

Das Auto-Discovery klappt leider nicht. Es ist aber eingeschaltet und klappt mit Tasmota gut.
Diese Zeile ist in meiner Config:
```topic # in 0 homeassistant/sensor/WlNabcdef/ WlNabcdef/sensor/device/```
und in MQTT sehe ich das:
![image](https://github.com/z-master42/solarflow/assets/13313834/d78c3704-4b1f-454a-8a76-e9da730dfc3c)
Leider taucht kein neues Gerät auf. Eine Idee?

Spaßeshalber hatte ich auch versucht eine YAML Datei zu erstellen, aber die Vorlage scheint irgendeinen Fehler ab dem Batterie Teil zu haben.

MfG

**Comment by z-master42** [comment]
Es wird auch kein Gerät auftauchen, sondern nur 15 einzelne Sensoren (Entitäten).


Was wird denn als Fehler angezeigt, hinsichtlich der YAML?

**Comment by z-master42** [comment]
Zumindest Entitäten hätten auftauchen müssen 🤔

Aber wenn die YAML jetzt funkrioniert, um so besser.
