### ISSUE TITLE
Pfad zur mosquitto DB nicht richtig !?

### ISSUE THREAD

**Issue by megabyte0469** [z-master42/solarflow#17]
Hallo,
hab die Anleitung soweit befolgt. 
Bekomme auch im Log vom Broker folgenden Eintrag:
**2024-04-10 08:45:14: Connecting bridge external-bridge (mqtt.zen-iot.com:1883)
2024-04-10 08:45:14: mosquitto version 2.0.18 running**

Was aber komisch ist, ist der Pfad der für die DB angezeigt wird:
**2024-04-10 09:15:15: Saving in-memory database to /data//mosquitto.db.**

Vor dem mosquitto.db steht ein doppel // 
Das kann so nicht stimmen ?! oder ?!

**Comment by z-master42** [comment]
Kann ich so nicht sagen. Habe ich noch nie drauf geachtet. Hat aber nichts mit der Verbindung zwischen deinem Mosquitto und dem Zendure Broker zu tun.
