### ISSUE TITLE
Verständnisfragen sensor.xxxx  und number.xxxxx und dann auch noch mqtt

### ISSUE THREAD

**Issue by martin-nrw-85** [z-master42/solarflow#18]
Hi ich bin blutiger Anfänger die Sache mit mqtt und Home Assistant angeht und habe da noch eine Verständnisungewissheit. 
Ich habe kein OpenDTU und frage mich ob es nicht möglich ist den Ausgang vom PV-Hub zu steuern?
- Dazu meine Fragen:
-1. Die Entität PV-Hub Ausgang wird als sensor "deklariert" kann ich dies im Skript so machen : "altes_limit: >-
                  {{
                  states('sensor.solarflow_power_pv_hub_ausgang')
                  | float(1) }}
                grid_sum: >-
                  {{ states('sensor.power_vom_netz_watt')
                  | float(1) }}"
was mich dann jedoch stutzig macht ist:
"- service: number.set_value
                              data:
                                value: "{{ minimum_wr }}"
                              target:
                                entity_id: >-
                                  sensor.solarflow_power_pv_hub_ausgang
                              alias: Setze Limit auf 50 W"
da dort number.set_value steht ich aber einen sensor.xxx habe.
2. werden diese Werte automatisch per mqtt von HomeAssistant zum ZendureHub versendet?

Liebe Grüße
Martin

**Comment by z-master42** [comment]
Hallo, es ist nicht möglich, bzw. seitens Zendure vorgesehen, den Hub über diesen Broker zu steuern. Die Daten sind rein zur Visualisierung.

**Comment by martin-nrw-85** [comment]
> Hallo, es ist nicht möglich, bzw. seitens Zendure vorgesehen, den Hub über diesen Broker zu steuern. Die Daten sind rein zur Visualisierung.

Hallo zurück und vielen lieben Dank für deine schnelle Antwort TOP
