### ISSUE TITLE
Keine Daten via MQTT

### ISSUE THREAD

**Issue by ndrtrp** [z-master42/solarflow#20]
Seit gestern erhalte ich keine Werte mehr über den EU-Zendure MQTT-Server. Ich verwende die MQTT-Informationen für meinen Home Assistant. Nun erhalte ich weder im Home Assistant noch im MQTT Explorer irgendwelche Werte. Das Problem ist mir aufgefallen, nachdem ich den Home Assistant neu starten musste. Die Abfrage von appkey und appsecret über die Kommandozeile funktioniert und ich erhalte die erwartete Antwort vom Server. Leider habe ich jetzt keine Ahnung, wo das Problem liegt. Ist der MQTT-Server derzeit überlastet? Wurde ich blockiert? In der App erhalte ich nach wie vor Daten, auch wenn es gelegentlich Unterbrechungen in der Energiestatistik gibt.
![Screenshot 17 05 2024 um 08 15 46 AM](https://github.com/z-master42/solarflow/assets/134544677/11698267-ed09-4205-8315-a46e408d8e64)

**Comment by z-master42** [comment]
Der Neustart kann da schwerlich für verantwortlich sein, zumal du mit dem MQTT-Explorer eine direkte Verbindung mit dem Zendure-Broker herstellst.

Das Nutzer aktiv plockiert werden ist mir nicht bekannt. Warum sollte dem so sein?

Ich habe allerdings auch keine Ahnung ob es nun mal wieder Verbindungsprobleme mit den Zendure-Brokern gibt.

Mal mqtteu.zen-iot.com ausprobiert?

**Comment by ndrtrp** [comment]
Danke für deine Rückmeldung

Wenn ich über mqtteu.zen-iot.com gehe, sagt mir der MQTT Explorer direkt "Connection refused - Bad username or password". 
Seltsam ist nun noch, dass ich eben mal die Abfrage via MQTT Explorer über mein Geschäfts-VPN versucht habe, und da tatsächlich auch Daten erhalte. An meinem Heimnetzwerk habe ich aber nichts verändert seit gestern und auch den Adguard habe ich testweise deaktiviert. Habe nun auch meinen Router neugestartet um eine neue Public IP zu bekommen, aber auch das hat nichts verändert.

**Comment by z-master42** [comment]
Ja, MQTTEU gibt es zwar scheint aber nicht mehr in Nutzung zu sein.

**Comment by z-master42** [comment]
AppSecret und AppKey ändern sich auch nicht. Wenn man sich die Antwort anschaut, bleibt auch der Broker der gleiche.

**Comment by ndrtrp** [comment]
Okay, also nachdem ich wirklich alles versucht habe, das Problem einzugrenzen, war am Ende vielleicht das Offensichtlichste die Lösung. Ich nutze Unifi und hatte in den Security-Settings Geoblocking-Rules (Beide Richtungen) für einige Länder (inkl. China) aktiv. Ich bin irgendwie nicht davon ausgegangen, dass der EU-Server in China steht. ;-). Nun, ich habe nun nur noch den eingehenden Traffic geblockt, jetzt bekomme ich auch wieder eine Connection und Daten. Alternativ könnte man auch China aus der Liste nehmen. Mir ist zwar noch nicht klar, warum es vorher ging und seit gestern nicht mehr, aber für den Moment ist es damit, zumindest bei mir, gelöst.

**Comment by Stadtkind1979** [comment]
> Okay, also nachdem ich wirklich alles versucht habe, das Problem einzugrenzen, war am Ende vielleicht das Offensichtlichste die Lösung. Ich nutze Unifi und hatte in den Security-Settings Geoblocking-Rules (Beide Richtungen) für einige Länder (inkl. China) aktiv. Ich bin irgendwie nicht davon ausgegangen, dass der EU-Server in China steht. ;-). Nun, ich habe nun nur noch den eingehenden Traffic geblockt, jetzt bekomme ich auch wieder eine Connection und Daten. Alternativ könnte man auch China aus der Liste nehmen. Mir ist zwar noch nicht klar, warum es vorher ging und seit gestern nicht mehr, aber für den Moment ist es damit, zumindest bei mir, gelöst.

Vielen Dank dafür, das hat bei mir nun auch zu einem erfolgreichen Aufruf geführt (habe ebenfalls Unifi im Einsatz)
