### ISSUE TITLE
Alle Sensoren unbekannt

### ISSUE THREAD

**Issue by FloBer431** [z-master42/solarflow#21]
Hallo, 
vielen Dank schonmal für die super Anleitung um neben einem bestehenden MQTT Broker einen weiteren anzulegen.
Ich bin der Anleitung soweit gefolgt und habe sie mit der manuellen EInrichtung der Sensoren durchgeführt. Leider zeigen alle meine Sensoren den zustand Unbekannt und keinerlei Werte. Über den MQTT-explorer bekomme ich jedoch werte.

Vielen Dank für eure Tipps!

**Comment by z-master42** [comment]
MQTT-Explorer verbunden mit dem Zendure-Broker oder mit dem Mosquitto-Addon (also Home Assistant)?

**Comment by FloBer431** [comment]
MQTT Explorer verbunden mit Zendure direkt liefert Daten, das Addon in HA liefert keine Daten

**Comment by z-master42** [comment]
Dann scheint die Verbindung zwischen Mosquitto und dem Zendure-Broker nicht zu stehen. Was sagt das Mosquitto Log nach dem Starten des Addons?

**Comment by FloBer431** [comment]
Habe gerade noch etwas gefunden woran es liegen könnte, komme da sber auch nicht weiter. Direkt in HA gibt es den Bereich customize von mqtt, muss da noch was eingetragen werden? richtiger folder etc?
![image](https://github.com/z-master42/solarflow/assets/73280677/d089c801-55c2-4c5c-8328-04039fa6f25f)

**Comment by FloBer431** [comment]
Ja genau, ich bin 1:1 der Anleitung gefolgt und habe dann mit mkdir den Ordner angelegt.

Ansonsten zeigt der Log keine Fehlermeldungen an, soweit ich sehen kann. Leider erscheint die IP adresse des Zendure Hubs aber auch nirgends

**Comment by z-master42** [comment]
![grafik](https://github.com/z-master42/solarflow/assets/66380371/07250cd3-11b4-421d-8f79-595e8eb4a943)

**Comment by FloBer431** [comment]
So sieht der Log aus:
![image](https://github.com/z-master42/solarflow/assets/73280677/2ad6f361-1d05-45cf-87b4-9dcf9b13d15e)

**Comment by z-master42** [comment]
Ok, und dann sieht du wenn du dich per MQTT Explorer mit dem Home Assistant verbindest keinen Eintrag der so heißt wie dein AppKey?

**Comment by FloBer431** [comment]
Doch da sehe ich einen Eintrag, rot ist mein AppKey:
![image](https://github.com/z-master42/solarflow/assets/73280677/714b0dfe-55e0-415e-a7a1-f06481833d30)
Aber in HomeAssistant selbst sind alle Entitäten unbekannt:
![image](https://github.com/z-master42/solarflow/assets/73280677/9e4d452a-45ad-461e-b424-edd20f3d75a9)

**Comment by z-master42** [comment]
Da sollte einer auf "gleicher Höhe" wie homeassistant oder tasmota sein.

**Comment by FloBer431** [comment]
![image](https://github.com/z-master42/solarflow/assets/73280677/fd1e31c3-cdbb-4fb1-b4df-d958ffb0f129)
![image](https://github.com/z-master42/solarflow/assets/73280677/05111a5f-0d11-4729-a41a-7693b010a4d8)

**Comment by FloBer431** [comment]
> Da sollte einer auf "gleicher Höhe" wie homeassistant oder tasmota sein.

Hmm komisch, wenn ich eine direkte Verbindung mit MQTT-Explorer mache, dann sehe ich die Daten, in Home Assistant mit genau dem Script aus der Anleitung nichts ...

**Comment by z-master42** [comment]
Na ja, irgendwas passt da noch nicht.
Und so lange die Einträge im MQTT-Explorer bei direkter Verbindung mit dem Zendure-Broker nicht so auch bei Home Assistant/Mosquitto auftauchen, werden die Entitäten keinen Wert haben.

**Comment by ottifant011** [comment]
Vielen danke für die tolle Anleitung.
Eine Frage mir werden keine Akkustände angezeigt
was muß ich bei  "Batterie <Nr> socLevel"  <Nr> eintragen irgend eine nummer oder was für ein wert?

**Comment by z-master42** [comment]
@ottifant011 Wenn dann die Seriennummer der jeweiligen Batterie.

**Comment by ottifant011** [comment]
`name: "Batterie 01 maxTemp"` also nicht so eintragen

**Comment by z-master42** [comment]
Doch.
So wie es da steht, alles in den spitzen Klammern, inklusiver der Klammern durch deine Daten ersetzen:

```
    - name: "Batterie <Nr> maxTemp"
      unique_id: "<deviceID>Batterie<Nr>maxTemp"
      state_topic: "<appKey>/<deviceID>/state"
      value_template: >
        {% if (value_json.packData | is_defined) %}
          {% for i in value_json.packData %}
            {% if i.sn == "<EureBatterieSeriennummer>" %}
              {{ (i.maxTemp | float - 273.15) | round(2) }}
            {% endif %}
          {% endfor %}
        {% endif %}
      unit_of_measurement: "°C"
      device_class: "temperature"
      device: 
        name: "SolarFlow"
        identifiers: "<EurePVHubSeriennummer>"
        manufacturer: "Zendure"
        model: "SmartPV Hub 1200 Controller"
```

**Comment by ottifant011** [comment]
`<Nr>` und da kommt die seriennummer der Baterie rein ok vielen Dank

**Comment by z-master42** [comment]
Nein, die kommt an Stelle <EureBatterieSeriennummer>. Bei <Nr> kannst du hinschreiben was du willst. Bei mir heißen die Batterien halt 1, 2 und 3.

**Comment by FloBer431** [comment]
Ich habe leider immer noch keinen fehler erkennen können, alle Seriennummern, uniqueIDs und AppKeys sind überall eingetragen, genauso wie ich sie aus der direkten MQTT Express Verbindung herausbekommen habe.

**Comment by z-master42** [comment]
> Ich habe leider immer noch keinen fehler erkennen können, alle Seriennummern, uniqueIDs und AppKeys sind überall eingetragen, genauso wie ich sie aus der direkten MQTT Express Verbindung herausbekommen habe.

Bevor deine manuellen MQTT YAML Einträge irgendwas machen können, muss erstmal die Verbindung stehen.

Du hast mir noch nicht gesagt, ob du man Mosquitto die gleichen Einträge findest, wie am Zendure (per MQTT-Explorer).

**Comment by FloBer431** [comment]
> > Ich habe leider immer noch keinen fehler erkennen können, alle Seriennummern, uniqueIDs und AppKeys sind überall eingetragen, genauso wie ich sie aus der direkten MQTT Express Verbindung herausbekommen habe.
> 
> Bevor deine manuellen MQTT YAML Einträge irgendwas machen können, muss erstmal die Verbindung stehen.
> 
> Du hast mir noch nicht gesagt, ob du am Mosquitto die gleichen Einträge findest, wie am Zendure (per MQTT-Explorer).

Genau da ist ja das Problem, ich habe auch das script, welches über das Terminal erstellt nochmals kontrolliert und AppKey und AppSecret wurden genau nach dem Muster eingetragen:

```
connection zendure-broker
address mqtt.zen-iot.com:1883
remote_username <appKey>
remote_password <appSecret>
remote_clientid <appKey>
topic <appKey>/# in
```
Siehe hier:
![image](https://github.com/z-master42/solarflow/assets/73280677/953a7054-bcff-4168-adf4-f2d68ec6d723)


Einträge sind direkt aus der funktionierenden MQTT Explorer - Zendure verbindung

**Comment by z-master42** [comment]
Ok, dann sollte das so aussehen:
![grafik](https://github.com/z-master42/solarflow/assets/66380371/73a8483b-e2ec-444e-aecc-ceea17b9e753)
Bitte nicht von dem solarflow-hub Topic irritieren lassen. Es geht um das darunter.

Frage: Was für einen Router hast du?

**Comment by FloBer431** [comment]
Jetzt funktioniert es, keine Ahnung was ich jetzt genau geändert habe, hab einmal alles nochmal gelöscht und neu erstellt.

Danke für eure Hilfe!

**Comment by z-master42** [comment]
Wie gesagt, um ein Update aller Entitäten zu forcieren in der Zendure App auf die Batteriedetailübersichtsseite gehen und dort ein wenig verweilen.

**Comment by FloBer431** [comment]
> Wie gesagt, um ein Update aller Entitäten zu forcieren in der Zendure App auf die Batteriedetailübersichtsseite gehen und dort ein wenig verweilen.

Ja das hab ich gerade gemacht, Frage ist noch, wie oft aktuslierist das System jetzt? also wie "live" sind die Daten und was ist die Abfragerate?

**Comment by z-master42** [comment]
Von bis.
An für sich bei Werteänderung.
Es gibt also kein periodisches Abfragen soweit ich das weiß.

**Comment by FloBer431** [comment]
okay, danke dir

**Comment by FloBer431** [comment]
Jetzt bin ich gerade auf ein weiteres Thema gestoßen, gerne würde ich in das HA Energie dashboard auch die Batterie einbinden. Dazu benötige ich ja die Werte Energie in Batterie und Energie aus Batterie. Dies sollten doch die Variablen "Output Pack Power" und "Input Pack Power" sein, diese dann mit einer Riemann Summenintegration und fertig nur leider liefern die beiden Werte absolut keine Daten, auch nicht beim Verweilen in der Batterieansicht. Ist das bekannt? Kann man was machen?
![image](https://github.com/z-master42/solarflow/assets/73280677/6a18a394-0769-4123-b525-2ddd2d9fee86)

**Comment by z-master42** [comment]
Sind das die einzigen beiden?
Bei mir haben die Daten.

**Comment by FloBer431** [comment]
Ja sind eigentlich die einzigen beiden:
![image](https://github.com/z-master42/solarflow/assets/73280677/06493571-d7d1-4481-a668-9b55a38caf42)

**Comment by z-master42** [comment]
Hmm, kann dann eigentlich nur noch daran liegen, dass die if im value_template zuschlägt und dem Sensor quasi dauerhaft ne 0 verpasst. Was passiert, wenn du die if raus nimmst und auch das expire_after. Die beiden Sensoren also vom YAML Aufbau so sind wie Output Home Power?

**Comment by FloBer431** [comment]
Sieht jetzt mal so aus im yaml:
![image](https://github.com/z-master42/solarflow/assets/73280677/6fef3d57-52d2-4582-9355-d2a1d89d60a7)
Daten kommen jetzt an, sind aber alles andere als live, aber das ist allgemein aktuell sehr extrem bei mir, Akku hat gerade eben gewechselt von Laden auf Einspeisen, und das ganze war erst 3/4 Minuten später so in HA ersichtlich

**Comment by FloBer431** [comment]
Die Daten:
![image](https://github.com/z-master42/solarflow/assets/73280677/8099fa13-ad94-4ac3-bab1-8a1d5154ec9c)
live dazu aus der App:
125W aus Akku
0W in Akku

**Comment by z-master42** [comment]
> > Hmm, kann dann eigentlich nur noch daran liegen, dass die if im value_template zuschlägt und dem Sensor quasi dauerhaft ne 0 verpasst. Was passiert, wenn du die if raus nimmst und auch das expire_after. Die beiden Sensoren also vom YAML Aufbau so sind wie Output Home Power?
> 
> Was meinst du denn mit expire after
> if habe ich ja entfernt

U. a. Zeile 38 im letzten YAML Screenshot.

An der “Laufzeit" der Daten kann ich nichts ändern.

Das beide Entitäten eine Leistung anzeigen liegt daran, dass Zendure keine 0 (Watt) übermittelt. Die Entität bleibt auf dem letzten Wert stehen. Kannst du über Automatisierungen abfagen/korrigieren.

**Comment by FloBer431** [comment]
Was macht das expire_after denn genau? 
Hast du dazu ein Beispiel, also zu so einer Automatisierung die das korigiert?

**Comment by z-master42** [comment]
> Was macht das expire_after denn genau? 
> Hast du dazu ein Beispiel, also zu so einer Automatisierung die das korigiert?
> 
> 

Eigentlich sollte dass das Topic/den Wert nach 120 s für ungültig erklären. Funktioniert aber irgendwie nicht. Also macht es aktuell sichtbar gar nichts.

```
alias: Batterieentladung
description: ""
trigger:
  - platform: numeric_state
    entity_id:
      - sensor.solarflow_pack_input_power
        above: 0
condition:
  - condition: not
    conditions:
      - condition: state
        entity_id: sensor.solarflow_output_pack_power
        state: "0"
action:
  - service: mqtt.publish
    metadata: {}
    data:
      qos: "0"
      topic: <appKey>/<deviceID>/state
      payload: "{\"outputpackPower\":0}"
mode: single
```

```
alias: Batterieladung
description: ""
trigger:
  - platform: numeric_state
    entity_id:
      - sensor.solarflow_output_pack_power
    above: 0
condition:
  - condition: not
    conditions:
      - condition: state
        entity_id: sensor.solarflow_pack_input_power
        state: "0"
action:
  - service: mqtt.publish
    metadata: {}
    data:
      qos: "0"
      topic: <appKey>/<deviceID>/state
      payload: "{\"packInputPower\":0}"
mode: single
```

**Comment by FloBer431** [comment]
Werde ich mal so übernehmen und testen, danke.

Hab gerade noch einen Fehler im Batterieentladen gefunden, müsste so heißen oder:
payload: "{\"output**_P_**ackPower\":0}"

**Comment by z-master42** [comment]
Oh, ja. Muss es.

**Comment by Settl3r** [comment]
Ich habe seit vorgestern das Problem, dass Abends (zwischen 19 und 20 Uhr) zu Begin der Batterieentladung über den Hub das Dashboard auf einmal angibt, dass aus der Batterie angeblich ca. 1,4kWh entladen worden sind. Es schaut so aus als ob die Automation die Werte auf "0" zu setzen nicht mehr greift.

**Comment by z-master42** [comment]
Bilder Dashboard und Verlauf Batterieladung und Entladung?

**Comment by Settl3r** [comment]
Anbei die Screenshots:
![Screenshot 2024-06-06 122636](https://github.com/z-master42/solarflow/assets/153107226/ad1b1c5f-de63-498b-8eea-fd6d643bc07f)
![Screenshot 2024-06-06 122858](https://github.com/z-master42/solarflow/assets/153107226/1c43e507-7685-4b02-a398-e99a5d4d164c)
![Screenshot 2024-06-06 123008](https://github.com/z-master42/solarflow/assets/153107226/3b03bbc3-6ad4-4f2e-bda7-c2e072c0ae6b)

**Comment by z-master42** [comment]
Wie sieht der ...discharge_sum aus? Der müsste dann ja dauerhaft einen Wert angezeigt haben?

Sind die Entitätennamen in den Automatisierungen richtig?

**Comment by Settl3r** [comment]
![Screenshot 2024-06-06 140626](https://github.com/z-master42/solarflow/assets/153107226/272367dc-cfa1-4ae3-9dae-1cebbb4a84ef)
![image](https://github.com/z-master42/solarflow/assets/153107226/1ebc578f-defa-4f54-b9c6-3bf65a3b51b4)
Da stehen bis um 19:30 über 100W drin.
Die Automatisierung sieht so aus:
- id: '171656abcxyz6'
  alias: Reset Battery Discharge
  description: Reset Battery Discharge
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.solarflow_pack_input_power
    above: 0
  condition:
  - condition: not
    conditions:
    - condition: state
      entity_id: sensor.solarflow_output_pack_power
      state: "0"
  action:
  - service: mqtt.publish
    metadata: {}
    data:
      qos: "0"
      topic: m2RvFS8E/5b8q2w8m/state
      payload: "{\"outputPackPower\":0}"
  mode: single
- id: '171656abcxyz1'
  alias: Reset Battery Charge
  description: Reset Battery Charge
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.solarflow_output_pack_power
    above: 0
  condition:
  - condition: not
    conditions:
    - condition: state
      entity_id: sensor.solarflow_pack_input_power
      state: "0"
  action:
  - service: mqtt.publish
    metadata: {}
    data:
      qos: "0"
      topic: m2RvFS8E/5b8q2w8m/state
      payload: "{\"packInputPower\":0}"
  mode: single

**Comment by z-master42** [comment]
Heißen deine Sensoren auch so wie in der Automatisierung?

Also `sensor.solarflow_pack_input_power`?
Oder heißt der `sensor.solarflow_power_battery_discharge`?


Offtopic: Du hast die Automatisierungen verkehrt herum benannt.

**Comment by Settl3r** [comment]
Stimmt, hab ich umbenannt, danke.

Der Sensor `sensor.solarflow_power_battery_discharge` ist ein Templatesensor dessen Quelle der Sensor `sensor.solarflow_pack_input_power` ist.

Daher sollte es doch passen, wenn die beiden Automationen `sensor.solarflow_pack_input_power` und `sensor.solarflow_output_pack_power` auf 0 zurücksetzen? Oder bringe ich hier was durcheinander?

**Comment by z-master42** [comment]
Ja, wenn es den Sensoren noch gibt, dann reicht das. Die Automatisierungen greifen aber auch nur bei einem Wechsel von Laden zu Entladen und andersherum. D. h. dein Fall ist ja an für sich nicht abgedeckt...

**Comment by Settl3r** [comment]
Kurze Info: aktuell funktioniert es wieder. Ich hab die Automation nochmal neu angelegt.

**Comment by CKtwosolar** [comment]
Moin z-master42,
ich habe eigentlich auch alles nach Anleitung angelegt, bekomme im mosquitto aber einfach keine neuen Entitäten angezeigt.
![appkey](https://github.com/z-master42/solarflow/assets/173611135/ba2759d9-6497-43a6-9a79-4064be5646f4)
![Protokoll_mqtt](https://github.com/z-master42/solarflow/assets/173611135/c81936c0-fb57-453c-b0c7-e0c2fcb84d3e)
![zendure conf](https://github.com/z-master42/solarflow/assets/173611135/2bf9cc06-f051-44a6-94fe-2c2aff4b53b5)
![mqtt explorer](https://github.com/z-master42/solarflow/assets/173611135/3aed348b-24d8-462b-b8f8-5fbce6536185)
![mqtt](https://github.com/z-master42/solarflow/assets/173611135/e1ab3354-b395-44ac-bd55-2b77c6ae5071)

Im MQTT Explorer und Verbindung zu Zendure kommt alles an. Die 3 Entitäten sind Daten, die ich aus der DTU erhalte.
Irgend ne Idee was ich noch versuchen könnte? Danke schonmal.

**Comment by z-master42** [comment]
Automatisch angelegte Entitäten tauchen nicht in der MQTT- Integration auf. Diese findest du nur anhand des jeweiligen Namens.

**Comment by CKtwosolar** [comment]
Sorry, ist vermutlich ne dumme Frage, aber bin HA Beginner…welchen Schritt muss ich jetzt noch machen?
Wie bei der OpenDTU die Werte über die mqtt.yaml  holen?
![IMG_3049](https://github.com/z-master42/solarflow/assets/173611135/07035dd1-99c2-40c6-8d85-0da7493ee920)

**Comment by z-master42** [comment]
Wenn das ein Plan ist.

Auf Grund der zusätzlichen Zeile, die du in deine zendure.conf übernommen hast, war ich der Annahme, du möchtest die Sensoren in Home Assistant automatisch angelegt haben.

PS: In OpenDTU gibt es auch eine Option die Sensoren/Entitäten durch Home Assistant automatisch erstellen zu lassen.

**Comment by CKtwosolar** [comment]
Eigentlich war mein Plan auch, dass die Sensoren automatisch in HA angelegt werden. Ich hätte gedacht, dass das alles unter den Entitäten zu finden ist oder als neues Gerät angezeigt wird. An welcher Stelle finde ich die Sensoren denn jetzt bzw. kann sie hinzufügen?

Bei der OpenDTU war es tatsächlich Absicht nicht alles erstellen zu lassen.

**Comment by z-master42** [comment]
Wie gesagt, soweit ich weiß werden sie in der MQTT- Integration nicht angezeigt und du findest sie nur unter dem jeweiligen Namen z. B. Electric Level, wenn du aktiv nach ihnen über Geräte und Dienste und dort auf dem Reiter Entitäten nach ihnen suchst.

Die "Bauanleitung" von Zendure gibt nicht mehr her und sie werden daher auch nicht zu einem Gerät zusammengefasst.

Die Entitäten heißen so wie in der Tabelle in der Anleitung.

**Comment by CKtwosolar** [comment]
Wäre gut wenn es so wäre, scheint bei mir leider nicht so zu klappen. Ich versuchs die Tage jetzt auch mal manuell einzubinden.

Danke für deine Hilfe und die super Anleitung.

![entities](https://github.com/z-master42/solarflow/assets/173611135/42b661ec-6863-42f4-bd17-cb96297758e1)
