### ISSUE TITLE
MQTT AIO 2400 - No data output on mqtt server - mqtt.zen-iot.com

### ISSUE THREAD

**Issue by heisenet** [z-master42/solarflow#22]
I get no data output with MQTT-Explorer, FHEM, iobroker and Home Asssistant with my new AIO 2400 (in Germany). I tried it with different (locale) users South Africa and Germany (curl).I can log in but get no data.
![Screenshot 2024-05-23 224354](https://github.com/z-master42/solarflow/assets/142940783/31b76dbc-fe15-4680-8c3f-5156e1a299ea)
![Screenshot 2024-05-23 224637](https://github.com/z-master42/solarflow/assets/142940783/cea819d8-3695-4b82-bbb1-20989c610bc4)

**Comment by heisenet** [comment]
I tried this manual: https://github.com/z-master42/solarflow/blob/main/solarflow.md - unfortunately without success

**Comment by z-master42** [comment]
As far as I know, the AiO is not yet supported with regard to the provision of data via MQTT. See also https://github.com/Zendure/developer-device-data-report/issues/39#issuecomment-2038787178
