### ISSUE TITLE
Solar Flow Hub 2000 with AB2000 "SolarFlow Pack Input Power" and "SolarFlow Pack Output Power" inverted

### ISSUE THREAD

**Issue by provi1** [z-master42/solarflow#23]
Hi,
it seems the values delivered from the Zendure API for "SolarFlow Pack Input Power" and "SolarFlow Pack Output Power" are inverted.
Input seems to be put going from the batterie and out power seems to be input to the batterie.
Maybe I understand your and the endure developer doc wrong. but it seems to be wrong in both docs.

**Comment by z-master42** [comment]
Input is from the battery.
Output is into the battery.

The designation is from the hub's point of view.

Hence also:
Solar Input
Output Home

**Comment by Simon-the-Sorcerer** [comment]
> Input is from the battery.
> Output is into the battery.

Thank you so much. Now my energy dashboard is finally right  👍
