### ISSUE TITLE
Connection Refused: not authorised

### ISSUE THREAD

**Issue by editwentyone** [z-master42/solarflow#25]
hi, ich komme nicht weiter, die config schon 2x neu aufgesetzt, die Daten darin sind richtig und gehen im MQTT Explorer einwandfrei 

```
2024-05-29 21:36:47: Connecting bridge zendure-broker (mqtt.zen-iot.com:1883)
2024-05-29 21:36:48: Connection Refused: not authorised
2024-05-29 21:36:48: Client local.<abcd> closed its connection.
```

hast du eine Idee?

**Comment by editwentyone** [comment]
musste mit /eu die infos bekommen. 
Endpoint(Europe): https://app.zendure.tech/eu/developer/api/apply

global geht bei mir nicht: bind device first
Endpoint(Golbal): https://app.zendure.tech/v2/developer/api/apply

hat es damit was zu tun?

**Comment by z-master42** [comment]
Wenn du in der Zendure App als Region nicht Global sondern Deutschland oder so eingestellt hast, dann ja.

**Comment by editwentyone** [comment]
hmmm und nun? mal mit global probieren?

**Comment by z-master42** [comment]
Wenn sie per MQTT Explorer funktionieren ist ja schon bewiesen, dass sie gehen.

Aktuell erschließt sich mir allerdings nicht, warum sie bei Mosquitto dann nicht gehen.

**Comment by editwentyone** [comment]
müssen ports offen sein? ufw oder sowas?

**Comment by z-master42** [comment]
Was fürn Router hast du?

**Comment by provi1** [comment]
Habe auch erst an Netzwerk Probleme gedacht aber:
Connection Refused, bedeutet meinem Wissen nach die Verbindung wurde abgelehnt. Ablehnen ist ja etwas aktives was passiert. Somit hat der Server geantwortet.

Manchmal ist es ja was blödes wie falsches Passwort oder API Key , weil Fehler beim Abschreiben, n Leerzeichen mit drin beim kopieren oder so.

**Comment by z-master42** [comment]
Hier waren auch schon Unifi Router die blockiert haben, da die Verbindung ja nach Hong Kong aufgebaut wird.

**Comment by editwentyone** [comment]
ich habe openwrt laufen, daher volle Kontrolle über das Netzwerk. auch mit vlans.  dazu noch pihole. 

MacBook mit Mqtt explorer funktioniert einwandfrei (wifi / vlan A)
server home assistant und Mqtt broker bekommt dann den Fehler zurück (wifi / vlan B) 

alles über selbes DSL und selben DNS (pihole)

**Comment by z-master42** [comment]
Viel mehr kommt dann auch nicht mehr im Log.

**Comment by z-master42** [comment]
Im Log nichts mehr. Hast du die Sensoren per YAML schon angelegt?

**Comment by editwentyone** [comment]
habe auf den auto modus konfiguriert, bin noch an der firewall dran

**Comment by editwentyone** [comment]
das ist jetzt echt peinlich… <> nicht gelöscht. omfg.
