### ISSUE TITLE
Sensor-Abfrage mit Android-App "IoT MQTT Panel"

### ISSUE THREAD

**Issue by FrankSkp** [z-master42/solarflow#26]
Hallo z-master42,
vielen Dank für diese ausführliche Beschreibung!
Ich habe sie genutzt, um sie auf die Android-App „IoT MQTT Panel“ anzuwenden. Ich habe damit eine Verbindung zum Zendure-Broker herstellen können, mit dem Topic „<appkey>/#“ erhalte ich alle Messages, die der Broker zu meinem SolarFlow liefert. Es ist mir jedoch noch nicht gelungen, einzelne Sensoren abzufragen. Ich habe es bisher mit folgenden Topics versucht, um beispielsweise die aktuelle Ausgabeleistung an den Wechselrichter abzufragen:
<appkey>/<deviceID>/outputHomePower
<appkey>/<deviceID>/outputHomePower/set
<appkey>/sensor/device/<deviceID>outputHomePower
<appkey>/<deviceID>/<deviceID>outputHomePower
Das hat leider nicht funktioniert. Deshalb meine Frage: Wie muss ein Topic formuliert werden, um Informationen zu einem einzelnen Sensor zu erhalten?
Vielen Dank schon mal und viele Grüße!

**Comment by z-master42** [comment]
Alle verfügbaren Werte werden unter dem Topic 'state' veröffentlicht. Eine tiefere Aufgliederung gibt es zendureseitig nicht. D. h. es gibt keine Einzel-Topics für die Einzelwerte. Die Werte unter 'state' sind im Format '{"Sensorname":Wert}' und das auch mit entsprechend mehreren Werten zusammen durch Komma getrennt, also im klassichen [JSON](https://de.wikipedia.org/wiki/JavaScript_Object_Notation)-Format.

**Comment by FrankSkp** [comment]
Das ist ja von Zendure nicht gerade komfortabel gelöst. Aber vielen Dank für die Info.
Viele Grüße, F

**Comment by z-master42** [comment]
Es gibt hier z. B. einen Topic-Mapper, der, denke ich genau das macht, was du haben möchtest. Kannst du dir ja mal angucken:

https://github.com/reinhard-brandstaedter/solarflow-bt-manager/blob/master/src%2Fsolarflow-topic-mapper.py

**Comment by FrankSkp** [comment]
Danke für die Info.
Da werde ich wohl auf ein anderes Tool umsteigen müssen; mit der Android-App komme ich da nicht weiter.
