### ISSUE TITLE
Keine Daten mehr seit heute

### ISSUE THREAD

**Issue by H0d0rKF** [z-master42/solarflow#28]
Seit heute Morgen erhalte ich keine Daten mehr ober den Zendure Broker. 

Bisherige Lösungsversuche:
1. MQTT Integration neu laden
2. MQTT Borker neu starten
3. Home Assistant neu starten

Brachte alles keinen Erfolg. Bis gestern ging noch alles.

**Comment by z-master42** [comment]
Scheint kein Einzelproblem zu sein.

**Comment by H0d0rKF** [comment]
OK, ja gerade in meinem Post in der App gesehen, dass da jetzt auch schon zwei geantwortet haben, die die gleichen Probleme haben. Dann scheint es am Zendure Broker zu liegen.

**Comment by ge8020** [comment]
> Seit heute Morgen erhalte ich keine Daten mehr ober den Zendure Broker.
> 
> Bisherige Lösungsversuche:
> 
> 1. MQTT Integration neu laden
> 2. MQTT Borker neu starten
> 3. Home Assistant neu starten
> 
> Brachte alles keinen Erfolg. Bis gestern ging noch alles.

Kann ich bestätigen. Aber es kommt im MQTT Explorer mit Direktverbindung zum Zendure Broker schon nichts an. Wird also tatächlich am Dienst liegen....

**Comment by z-master42** [comment]
Also bei mir kommt was an. In welcher Region seid ihr in der Zendure App unterwegs?

**Comment by ge8020** [comment]
> Also bei mir kommt was an. In welcher Region seid ihr in der Zendure App unterwegs?

Hier Österreich

**Comment by megabyte0469** [comment]
Hier das gleiche Problem. Schätze die basteln wieder an den Online Servern. War ja in den letzten Tagen ständig irgendwelche Änderungen und Parameter die in der Zendure App mal da und dann wieder verschwunden sind.

**Comment by H0d0rKF** [comment]
> #

> Also bei mir kommt was an. In welcher Region seid ihr in der Zendure App unterwegs?

Europa

**Comment by programmieramt** [comment]
Kann man die Region die man verwendet nachträglich ändern?

**Comment by editwentyone** [comment]
bin auch betroffen, war auf global. habe beides versucht wieder anzufragen und es heißt bei beiden Servern (global und EU) please bind device first

obwohl die zendure app sogar Daten liefert und was anzeigt 

wieder ein Grund mehr sich von der cloud zu lösen: https://github.com/reinhard-brandstaedter/solarflow-control

**Comment by phenomeus** [comment]
bin auch betroffen, bin auf global. habe beides versucht wieder anzufragen und es heißt bei beiden Servern (global und EU) please bind device first

obwohl die zendure app sogar Daten liefert und was anzeigt

wieder ein Grund mehr sich von der cloud zu lösen: https://github.com/reinhard-brandstaedter/solarflow-control

**Comment by z-master42** [comment]
> Kann man die Region die man verwendet nachträglich ändern?

Kann man.

**Comment by z-master42** [comment]
> bin auch betroffen, bin auf global. habe beides versucht wieder anzufragen und es heißt bei beiden Servern (global und EU) please bind device first
> 
> obwohl die zendure app sogar Daten liefert und was anzeigt
> 
> wieder ein Grund mehr sich von der cloud zu lösen: https://github.com/reinhard-brandstaedter/solarflow-control

Es geht ja auch nur entweder oder. Aber mit einem sollte ja eigentlich eine Bindung bestehen.

**Comment by phenomeus** [comment]
klar habe ich nur eins, beide geben den gleichen "Fehler" / status aus. das wollte ich damit sagen

**Comment by Astromechdroide** [comment]
Auf der GitHub Seite von Zendure gibt es auch schon GitHub Issues.
[https://github.com/Zendure/developer-device-data-report/issues/51](url)

**Comment by z-master42** [comment]
Ich kann da hier von dieser Seite leider nichts dran machen, da ich hier nur eine Anleitung bereitstelle. Das Problem muss Zendure lösen. Was ich soweit feststellen kann ist, dass es aktuell nur EU-Server-Nutzer betrifft. Benutzer die auf dem globalen Server unterwegs sind, scheinen nicht betroffen zu sein.

**Comment by phenomeus** [comment]
das ist klar, ich denke alle suchen dich hier auf um auch sicher zu gehen, dass es nicht an einem selbst liegt. denke wir müssen alle warten was zendure macht

**Comment by JoB1l** [comment]
Bin auch betroffen. seit 4-5 Uhr heute früh kommen keine Daten mehr über MQTT. Die App läuft ganz normal. Mir sind die letzten Tage auch immer wieder änderungen am aufgefallen. Seit mitte April war bei mir nur noch der "Solar Input" in echtzeit. Da war die aktualisierung mal paar Tage sporadisch verzögert (zwischen 4-32 Sekunden laut mqtt Explorer)

der Smart-CT mode hing heute auch ständlig (mit Shelly Pro 3EM). hatte zwischendurch immer wieder das der Hub einfach mit voller leistung (1200W) in den wechselrichter gebuttert hat und mir natürlich den akku lee gezogen, obwohl der Shelly -300W gemessen hatt (hab noch module direkt am Wechselrichter)

Vielleicht arbeiten die ja endlich mal an dem **Update** das man den Hub auch per MQTT steuern kann (output) limit setzen. Steht ja groß an Nummer 1 auf den "Future Plans"

Vielleicht kommt sogar wirklich auch noch eine HA integration.

**Comment by z-master42** [comment]
> Bin auch betroffen. seit 4-5 Uhr heute früh kommen keine Daten mehr über MQTT. Die App läuft ganz normal. Mir sind die letzten Tage auch immer wieder änderungen aufgefallen. Seit mitte April war bei mir nur noch der "Solar Input" in echtzeit. Da war die aktualisierung mal paar Tage sporadisch verzögert (zwischen 4-32 Sekunden laut mqtt Explorer)
> 
> der Smart-CT mode hing heute auch ständlig (mit Shelly Pro 3EM). hatte zwischendurch immer wieder das der Hub einfach mit voller leistung (1200W) in den wechselrichter gebuttert hat und mir natürlich den akku lee gezogen, obwohl der Shelly -300W gemessen hatt (hab noch module direkt am Wechselrichter)
> 
> Vielleicht arbeiten die ja endlich mal an dem **Update** das man den Hub auch per MQTT steuern kann (output) limit setzen. Steht ja groß an Nummer 1 auf den "Future Plans"
> 
> Vielleicht kommt sogar wirklich auch noch eine HA integration.

Wer's glaubt, das stand da schon unter "Future Plans" als es noch gar keinen SolarFlow gab. Die "Reaktionszeit" auf die Issues bei denen sprechen da ja auch für sich.

**Comment by TJHooker** [comment]
hier das gleiche mqtt.zen-iot.com:1883

2024-06-17 17:08:43: Connecting bridge zendure-broker (mqtt.zen-iot.com:1883)
2024-06-17 17:08:46: New connection from 172.30.32.2:36734 on port 1883.
2024-06-17 17:08:46: Client <unknown> closed its connection.
2024-06-17 17:08:51: Client local.RpoXXXX closed its connection.

die tun so als würde die nich nicht mehr kennen ??

**Comment by phenomeus** [comment]
bei mir geht EU server auch wieder

**Comment by JoB1l** [comment]
hab meinen appkey und secretkey nochmal abzufragen, bekomme folgende rückmeldung vom server:

{"code":400,"success":false,"data":{},"msg":"Please bind the device first"}* Connection #0 to host app.zendure.tech left intact


Hab den Hub dann aus der App gelöscht und neu hinzugefügt und nochmal probiert, immer noch das gleiche (EU anbindung)


könnte es damit zusammen hängen ?

< X-Cache: Error from cloudfront
X-Cache: Error from cloudfront

**Comment by H0d0rKF** [comment]
Bei mir kommen wieder Werte An, da Z-Master42 hier eh nichts machen kann schließe ich hiermit den Issue.

**Comment by JoB1l** [comment]
Kann ich bestätigen, bei mir läuft es auch wieder.

Es war ja klar, dass seitens Zendure Server was nicht gepasst hat ;)
