### ISSUE TITLE
Entitätsnamen

### ISSUE THREAD

**Issue by lopo2005de** [z-master42/solarflow#3]
Hi z-master42 ,
nun habe ich eine Lösung gefunden, die mir gefällt, alles druchgearbeitet - doch leider nun einen Fehler:

Einige MQTT-Entitäten haben einen Entitätsnamen, der mit dem Gerätenamen beginnt. Dies ist nicht zu erwarten. Um einen doppelten Namen zu vermeiden, wird als Work-Around das Präfix des Gerätenamens aus dem Entitätsnamen entfernt. Bitte aktualisiere deine Konfiguration und starte Home Assistant neu, um dieses Problem zu beheben.

Liste der betroffenen Entitäten:

    sensor.solarflow_wifi_state
    sensor.solarflow_remain_input_time
    sensor.solarflow_inverse_max_power
    switch.solarflow_master_switch
    sensor.solarflow_pack_state
    sensor.solarflow_electric_level
    sensor.solarflow_output_limit
    sensor.solarflow_pack_input_power
    sensor.solarflow_hub_state
    sensor.solarflow_output_pack_power
    sensor.solarflow_remain_out_time
    sensor.solarflow_solar_input_power
    switch.solarflow_buzzer_switch
    sensor.solarflow_pack_num
    sensor.solarflow_output_home_power
    sensor.solarflow_soc_set
    sensor.solarflow_input_limit

Was muss ich nun machen?
Gruss lopo

**Comment by z-master42** [comment]
Erstmal ignorieren:
https://community.home-assistant.io/t/psa-mqtt-name-changes-in-2023-8/598099

**Comment by z-master42** [comment]
So. Was du machen musst ist, 'SolarFlow' aus dem Sensornamen entfernen. Habe es bereits angepasst.

**Comment by lopo2005de** [comment]
DANKE für die schnelle Antwort!!!
Eine super Anleitung hast Du da gemacht!
Nun sehe ich mit dem MQTT Explorer auf meinem HA nicht nur die eigenen Sensoren wie Shelly und ein paar Wemos, nun auch den SolarFlow.
Aber ich muss noch kurz etwas fragen:  

Muss ich in der mqtt.yaml die Werte <appKey>/<deviceID> in den Zeilen durch die realen Werte ersetzen oder werden die durch die aus der zendure.conf übertragen? 
2 Stunden steht bei mir überall noch "unbekannt"

**Comment by lopo2005de** [comment]
Super!!! Danke, mach ich gleich :)

**Comment by lopo2005de** [comment]
Ich bin begeistert! alle wichtigen Daten im HA. :)
Cool wäre noch, wenn ich mit dem WT32-SC01 einen Solarmonitor bekommen würde.
Mal schauen, ob ich die Daten jetzt auch auf einem Wemos bekommen.

Viele Grüsse und Danke!
