### ISSUE TITLE
Vereinfachung Anleitung: Zugriff auf /share mit Studio Code Addon

### ISSUE THREAD

**Issue by ulope** [z-master42/solarflow#37]
Die Anleitung im Wiki geht sehr ausführlich darauf ein, wie man per SSH Dateien bearbeitet.

Die einfachere Lösung ist im HA Studio Code addon in den erweiterten Optionen den `config_path` auf `/root` zu setzen.

Nach speichern und addon neu starten kann man per `File -> Open Folder` (im addon) den root ordner auswählen und hat vollen Zugriff auf das gesamte Dateisystem

**Comment by z-master42** [comment]
Ja klar. Wäre auch eine Möglichkeit. Samba-Addon ginge genau so gut.

Danke für den Hinweis.

**Comment by z-master42** [comment]
Ergänzt
