### ISSUE TITLE
Message malformed: extra keys not allowed @ data['sequence']

### ISSUE THREAD

**Issue by ragman11** [z-master42/solarflow#4]
Hallo,
Danke für deine tolle Arbeit für eine Nulleinspeisung bei SF. Ich habe dein Script in eine Automation kopiert und bekomme beim speichern folgende Fehlermeldung.

Message malformed: extra keys not allowed @ data['sequence']

lg
Mike

**Comment by z-master42** [comment]
Ist richtig, da es sich um ein Skript handelt und keine Automatisierung.
![Screenshot_2023-09-22-10-24-34-03_c3a231c25ed346e59462e84656a70e50.jpg](https://github.com/z-master42/solarflow/assets/66380371/942466f5-776c-43d2-80dc-0de8f421c7d5)

**Comment by ragman11** [comment]
Hi, Danke für den schnellen Hinweis, als Script funktioniert es natürlcih wunderbar.

Danke
lg
Mike
