### ISSUE TITLE
Erklärung zu eineigen Werten gesucht

### ISSUE THREAD

**Issue by rseffner** [z-master42/solarflow#40]
Ich bin mir bei der Interpretation einiger Werte unsicher und suche Hilfe/Gewissheit:
(es soll ja alles aus Sicht des Hyper2000 betrachtet werden, nicht?)

acOutputPower = Leistung ins Haus? Was ist dann aber outputHomePower?
gridInputPower = Bezug vom Haus?
hubState = welche Werte mit welcher Bedeutung kann das annehmen?
inverseMaxPower = Einspeiselimit vom Akku ins Haus? Was ist dann aber outputLimit?
outputHomePower = siehe acOutputPower
outputLimit = siehe inverseMaxPower
packState = welche Werte mit welcher Bedeutung kann das annehmen?
passMode = welche Werte mit welcher Bedeutung kann das annehmen?
wifiState = welche Werte mit welcher Bedeutung kann das annehmen?

Ich danke für das bisher Geleistete und die Mühen hier Licht in (mein) Dunkel zu bringen.

**Comment by z-master42** [comment]
**Hyperspezifisch:**
acOutputPower = Weiß ich tatsächlich nicht was das genau sein soll.
gridInputPower = Ladeleistung aus dem Netz

**Allgemein Hub und Hyper:**
hubState = Modus, was der Hub/Hyper macht, wenn die Entladegrenze erreicht wurde: 0 Standby, 1 Ausschalten
inverseMaxPower = Maximal zulässige Wechselrichterleistung bzw. Behördlich begrenzte Ausgangsleistung
outputHomePower = Aktuelle Abgabe ans "Haus"
outputLimit = maximale Abgabe ans "Haus"
packState = Akkustatus: 0 Standby, 1 Laden, 2 Entladen
passMode = Bypass-Modus: 0 Automatisch, 1 Immer aus, 2 Immer ein
wifiState = 1 für mit dem WLAN verbunden, 0 für getrennt

**Comment by z-master42** [comment]
Zum Thema acOutputPower: Da hierzu aktuell wohl gar keine Werte übermittelt werden, könnte es sich um eine Entität handeln, die erst in der Zukunft eine Rolle spielt. Die Vermutungen gehen hier in die Richtung [Off-Grid-Steckdosenleiste](https://www.zendure.de/products/off-grid-steckdosenleiste), wobei dann OutputHomePower in dem Fall keinen Wert haben dürfte.
