### ISSUE TITLE
Static Config Issues 

### ISSUE THREAD

**Issue by tobit6795** [z-master42/solarflow#5]
Hi, 

erstmal danke für deine Mühen.

Derzeit funktionieren beide Switches bei mir nicht, mqtt conf bzw. switch conf sind gem.
https://github.com/z-master42/solarflow/blob/main/solarflow.md
Klappen die denn bei dir? Desweiteren bekomme ich diverse Entitäten garnicht erst bzw. kann sie garnicht in meinem Broker finden (SolarFlow WiFi State). Parallel nutze ich die Solarflow Statuspage(https://github.com/reinhard-brandstaedter/solarflow-statuspage) bei dieser werden genannte Attribute einwandfrei angezeigt

**Comment by z-master42** [comment]
Ich habe die tatsächlich noch nie benutzt. Die Konfiguration stammt von Zendure. Mir hat es erstmal gereicht, dass die Schalter den tatsächlichen Zustand anzeigen.

Wie erwähnt muss man für die meisten Entitäten eine Aktualisierung forcieren. Der wifiState wird z. B. nur sehr selten aktualisiert. Vielleicht verteilt Zendure den Status aber auch schon gar nicht mehr.

**Comment by z-master42** [comment]
Die Schalter sind auch nicht zum Schalten da, sondern dienen nur der Informationsdarstellung (bessere Visualisierung als 0 und 1 oder false und true).
