### ISSUE TITLE
Probleme mit Anleitung

### ISSUE THREAD

**Issue by akkon** [z-master42/solarflow#6]
Hi, erstmal vielen Dank für die ausführliche Anleitung. 

Leider habe ich die automatische Erkennung nicht zum laufen bekommen, hier der Fehler im Log:

1695898434: Loading config file /share/mosquitto/mosquitto.conf
1695898434: Error: Invalid bridge topic local prefix and pattern combination 'xxxxx/sensor/device#'.
1695898434: Error: Out of memory.
1695898434: Error found at /share/mosquitto/mosquitto.conf:7.
1695898434: Error found at /etc/mosquitto/mosquitto.conf:37.
[10:53:54] WARNING: Halt add-on

Habe jetzt die manuelle Konfiguration versucht, hier werden die Devices angelegt, wechseln aber sofort auf den Zustand unbekannt. 
Im MQTT Explorer kommen die Daten rein und habe natürlich das File mit meinen Appkey usw versorgt. Gibt es eine Möglichkeit zu sehen ob die Daten überhaupt in Mosquito reinkommen ?

Danke schon mal

**Comment by z-master42** [comment]
> xxxxx/sensor/device#

Eine # gehört da schon mal nicht hin.

Wenn du dich mit dem MQTT Explorer mit dem Mosquitto broker verbindest, siehst du, was da alles reinkommt.

**Comment by akkon** [comment]
Danke für die schnelle Antwort, den Fehler habe ich gefunden und behoben. Im Log von Mosquitto kommt die Meldung dass die Verbindung hergestellt wurde. Soweit so gut. Allerdings wird kein neues Gerät in der MQTT Integration angelegt. 

Soll die Zeile "topic # in 0 homeassistant/sensor/<appKey>/ <appKey>/sensor/device/" zusätzlich zur schon bestehenden topic Zeile eingefügt werden oder stattdessen ?

Gibt es noch eine Möglichkeit zu prüfen was im Mosquito von dem externen MQTT Server hereinkommt ?

**Comment by z-master42** [comment]
> Ergänzt hierzu in euer zendure.conf einfach noch eine Zeile mit: `topic # in 0 homeassistant/sensor/<appKey>/ <appKey>/sensor/device/`

Ja

Abgesehen vom MQTT Explorer kannst du auf der Konfigurationsseite der MQTT-Integration "auf ein Topic" hören", z. B. kannst du da deinen AppKey gefolgt von /# eintragen und dann solltest du alles sehen, was vom Zendure-Broker veröffentlicht wird.
