### ISSUE TITLE
 remainInputTime no data

### ISSUE THREAD

**Issue by ragman11** [z-master42/solarflow#8]
Hallo,

Bin mir nicht sicher ob es nur bei mir der Fall ist, aber ich bekomme keine  remainInputTime. Auf remainoutputTime bekomme ich Daten rein...

danke
lg
M

**Comment by z-master42** [comment]
Bist nicht alleine. Das ist bereits seit einigen Monaten so. Kann aber auch gut sein, dass mittlerweile beides über den gleichen Sensor geliefert wird, je nach dem was gerade der Fall ist. Es geht ja nur laden oder entladen. So genau verglichen habe ich das noch nicht. Ist ja aber auch eh eher ein Schätzeisen, die Zeitangabe.
