### ISSUE TITLE
Fehler beim Abruf der Daten für EU Server

### ISSUE THREAD

**Issue by andiweli** [z-master42/solarflow#9]
Seriennummer und Mailadresse wurden korrekt eingefügt.
Ich war zuvor am Globalen Server.

Als Fehler kommt das...

`
Invoke-WebRequest : Fehlendes Argument für den Parameter "InFile". Geben Sie einen Parameter vom Typ "System.String"
an, und versuchen Sie es erneut.
In Zeile:1 Zeichen:6
+ curl -i -v --json "{'snNumber': '*** hier steht meine Seriennummer***', 'account': 'stuerm ...
+      ~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-WebRequest], ParameterBindingException
    + FullyQualifiedErrorId : MissingArgument,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
`

**Comment by andiweli** [comment]
Ok kleines Update. Unter Windows 11 scheint das nicht zu funktionieren.

Unter Linux klappt es.

**Comment by z-master42** [comment]
Das einzige was an dem Befehl für den EU-Server anders ist, ist das eu anstelle v2 in der Server-Adresse. Hast du den richtigen Befehl genommen?

**Comment by andiweli** [comment]
Hat unter Linux geklappt. Windows 11 kann mit der Befehlszeile scheinbar nicht umgehen.

**Comment by z-master42** [comment]
Hmm, ok. Bei mit ging es "damals". In der Kommandoeingabezeile. Muss ich mir noch mal angucken, wenn ich einen Windows 11 Rechnernin der Nähe hab.

**Comment by z-master42** [comment]
Also ich konnte dein Windows 11 Problem jetzt nachstellen. Wobei es kein Windows 11 Problem ist. Der curl-Befehl funktioniert so wie er in der Anleitung steht in der Eingabeaufforderung (cmd). Der Fehler den du oben angibt erscheint, wenn man stattdessen die PowerShell benutzt.
